start: instruction+

instruction: [variable][use|execute] ";" 
    | variable "=" value ";"

use: object object* "use" name
execute: object object* name [["with"] block]
variable: "$" object

object: OBJECT -> azobject
name: STRING -> azname

block: "(" pair ("," pair)* ")"
pair: object ":" value
value: (name|NUMBER|block) -> azvalue

OBJECT: ("a".."z" | "A".."Z" | "1".."9" | "-")+
STRING: (/".*?(?<!\\)"/ | /'.*?(?<!\\)'/)

%import common.SIGNED_NUMBER -> NUMBER
%import common.WS
%ignore WS
