from handlers.az.Generic import *
from handlers.az.EventGrid import *
from handlers.az.EventHubs import *
from handlers.az.ResourceGroup import *
from handlers.az.Storage import *
from handlers.az.CosmosDB import *
from handlers.az.AppService import *
from handlers.az.FunctionApp import *
from handlers.az.Extension import *
from handlers.az.IoT import *